//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVtoSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AH_ODS_DBEntities : DbContext
    {
        public AH_ODS_DBEntities()
            : base("name=AH_ODS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Err_Sales> Err_Sales { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<JT> JTs { get; set; }
        public virtual DbSet<JT_Temp> JT_Temp { get; set; }
        public virtual DbSet<LocalBranch> LocalBranches { get; set; }
    }
}
