//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVtoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Err_Sales
    {
        public long Serial { get; set; }
        public string ExtSerial { get; set; }
        public string DateTime { get; set; }
        public string ErrorDesc { get; set; }
    }
}
