//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVtoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JT_Temp
    {
        public long Serial { get; set; }
        public string ExtSerial { get; set; }
        public string EnvelopeCode { get; set; }
        public int Line { get; set; }
        public int Lines { get; set; }
        public string Branch_COA { get; set; }
        public string AQ_COA { get; set; }
        public string AQ_Branch { get; set; }
        public string RecordType { get; set; }
        public double Amount { get; set; }
        public string PostDate { get; set; }
        public int AQ_PostStatus { get; set; }
        public string AQ_StatusDate { get; set; }
        public string DTS { get; set; }
        public string LineDescription { get; set; }
    }
}
