//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVtoSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long Serial { get; set; }
        public string ExtSerial { get; set; }
        public string Date { get; set; }
        public string CustomerRefNbr { get; set; }
        public string Description { get; set; }
        public string Customer { get; set; }
        public Nullable<double> Amount { get; set; }
        public string AQ_Branch { get; set; }
        public string AQ_COA { get; set; }
        public string LineSubAccount { get; set; }
        public string LineTaxCategory { get; set; }
        public Nullable<int> LineQuantity { get; set; }
        public Nullable<double> LineUnitPrice { get; set; }
        public Nullable<int> AQ_PostStatus { get; set; }
        public string AQ_StatusDate { get; set; }
        public string DTS { get; set; }
        public string LineDescription { get; set; }
    }
}
